INSERT INTO PAYMENT_MODE (MODE) VALUES ('UPI');
SELECT * FROM PAYMENT_MODE;

INSERT INTO CITY (NAME) VALUES ('BANGALORE');
SELECT * FROM CITY;

INSERT INTO STATE (NAME) VALUES ('KARNATAKA');
SELECT * FROM STATE;

INSERT INTO DISCOUNT (NAME, PERCENT) VALUES ('EARLY SALE', '10.1');

INSERT INTO TAX (NAME, PERCENT) VALUES ('GST', '10.1');



INSERT INTO COUNTRY (NAME) VALUES ('INDIA');
SELECT * FROM COUNTRY;
SELECT ID FROM COUNTRY WHERE NAME='INDIA';


INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, STREET, CITY_ID, STATE_ID, COUNTRY_ID) VALUES ('SURAJ', 'SHARMA', '#123', 1,1,1);
SELECT * FROM CUSTOMER;

INSERT INTO MERCHANT (FIRST_NAME, LAST_NAME) VALUES ('AMIT', 'GUPTA');
SELECT * FROM MERCHANT;

INSERT INTO SHOP (NAME, STREET, MERCHANT_ID, CITY_ID, STATE_ID, COUNTRY_ID) VALUES ('CHACHA KI DUKAN', '32', 1, 1, 1, 1);
SELECT * FROM SHOP;

INSERT INTO EMAIL (EMAIL_ADDRESS, CUSTOMER_ID) VALUES ('SURAJ@GMAIL.COM', 1);
INSERT INTO EMAIL (EMAIL_ADDRESS, MERCHANT_ID) VALUES ('AMIT@GMAIL.COM', 1);
SELECT * FROM  EMAIL;

INSERT INTO ITEM (NAME, DESCRIPTION, PRICE) VALUES ('TV','SAMSUNG LED',11.1);

INSERT INTO INVOICE_STATE (STATE) VALUES ('DRAFT');

INSERT INTO SHIPPING_ADDRESS (CUSTOMER) VALUES (1);

INSERT INTO INVOICE (
INVOICE_NUMBER,
INVOICED_DATE,
INVOICED_TIME,
DUE_DATE,
ENABLE_AUTO_ALERTS,
TOTAL_AMOUNT,
MERCHANT_ID,
INVOICE_STATE_ID,
CUSTOMER_ID,
SHIPPING_ADDRESS_ID
) VALUES (
'12',
'2018-10-20',
'2018-10-20',
'2018-10-20',
TRUE,
11.11,
1,
1,
1,
1
);

select * from invoice;
